from typing import (
    Callable,
    ContextManager,
    Generator,
    Iterable,
    ParamSpec,
    Protocol,
    TypeVar,
)

PT = ParamSpec('PT')  # param type
YT = TypeVar('YT')  # yield type
ST = TypeVar('ST')  # send type
RT = TypeVar('RT')  # return type


class ReporterProtocol(Protocol):
    @property
    def report_methods(self) -> bool: ...

    @report_methods.setter
    def report_methods(self, new_value: bool) -> None: ...

    @property
    def is_current_stage_passed(self) -> bool: ...

    @is_current_stage_passed.setter
    def is_current_stage_passed(self, value: bool) -> None: ...

    def create_file_with_env_info(self, allure_results_path_str: str) -> None: ...

    def ARRANGE(self, msg: str) -> ContextManager: ...  # noqa: N802
    def ACT(self, msg: str) -> ContextManager: ...  # noqa: N802
    def ASSERT(self, msg: str) -> ContextManager: ...  # noqa: N802

    def step(self, name: str) -> ContextManager: ...

    def attach_text(self, text: str, name: str = 'Info') -> None: ...
    def attach_image(self, source, name) -> None: ...
    def attach_zip(self, source, name) -> None: ...
    def attach_link(self, name: str, url: str) -> None: ...
    def attach_tms_link(self, name: str, url: str) -> None: ...

    def report_step(self, *args, **kwargs) -> Callable: ...
    def report_method(self, *args, **kwargs) -> Callable: ...
    def report_static_step(self, *args, **kwargs) -> Callable: ...
    def report_static_method(self, *args, **kwargs) -> Callable: ...
    def report_fixture(
        self,
        func: Callable[PT, RT] | Generator[YT, ST, RT],
    ) -> Callable[PT, RT] | Generator[YT, ST, RT]: ...

    def set_parent_suite(self, parent_suite_name: str) -> None: ...
    def set_suite(self, suite_name: str) -> None: ...
    def set_sub_suite(self, sub_suite_name: str) -> None: ...
    def set_feature(self, features_names: Iterable[str]) -> None: ...
    def set_story(self, stories_names: Iterable[str]) -> None: ...
    def set_title(self, title: str) -> None: ...
    def set_description(self, description: str) -> None: ...
