from pathlib import Path
from typing import Any, Callable, Generator, ParamSpec, Protocol, TypeVar

from pyqatools.loggers.log_levels import LogLevels

PT = ParamSpec('PT')  # param type
YT = TypeVar('YT')  # yield type
ST = TypeVar('ST')  # send type
RT = TypeVar('RT')  # return type


class LoggerProtocol(Protocol):
    def __init__(
        self,
        log_file_path: Path,
        log_level: LogLevels = LogLevels.DEBUG,
        clear_handlers: bool = False,
        console_output: bool = True,
        file_output: bool = True,
    ): ...
    def set_log_level(self, log_level: str) -> None: ...
    def configure_msg_prefixes(
        self,
        msg_prefix_step: str | None = None,
        msg_prefix_static_step: str | None = None,
        msg_prefix_method: str | None = None,
        msg_prefix_static_method: str | None = None,
        msg_prefix_static_fixture: str | None = None,
    ) -> None: ...
    def remove_logger(self) -> None: ...
    def deep_trace(self, msg: Any) -> None: ...
    def trace(self, msg: Any) -> None: ...
    def debug(self, msg: Any) -> None: ...
    def info(self, msg: Any) -> None: ...
    def step(self, msg: Any) -> None: ...
    def fixture(self, msg: Any) -> None: ...
    def test(self, msg: Any) -> None: ...
    def success(self, msg: Any) -> None: ...
    def warning(self, msg: Any) -> None: ...
    def error(self, msg: Any) -> None: ...
    def log_step(self, func: Callable) -> Callable: ...
    def log_method(self, func: Callable) -> Callable: ...
    def log_static_method(self, func: Callable) -> Callable: ...
    def log_static_step(self, func: Callable) -> Callable: ...
    def log_fixture(
        self, func: Callable[PT, RT] | Generator[YT, ST, RT]
    ) -> Callable[PT, RT] | Generator[YT, ST, RT]: ...
